export const ru={
    "title":"rusa",
    "Perfil":"профиль",
    "Salir":"уехать",
    "Lista de Usuarios":"Список пользователей",
    "Lista de Flores":"Список цветов",
    "Lista de Fincas":"список ферм",
    "Pagos y reclamos": "Платежи и претензии",
    "Identificación":"МНЕ БЫ",
    "Nombres":"Имена",
    "Apellidos":"Фамилии",
    "Foto":"Фото",
    "Email":"Эл. почта",
    "Estado":"состояние",
    "Saldo del Cliente":"Баланс клиента",
    "Cliente":"Клиент",
    "Fecha":"Дата",
    "Saldo inicial":"Первоначальный баланс",
    "Datos de la búsqueda":"Данные поиска",
    "Seleccione": "Пожалуйста выберите",
    "Número de documentos": "Количество документов",
    "Número de registros": "Количество записей",
    "Documento": "Документ",
    "Razón Social":"Наименование фирмы",
    "Tipo documento": "Тип документа",
    "Débito": "Дебет",
    "Crédito": "Кредит",
    "Saldo": "Остаток средств",
    "Buscar": "Ищи",
    "Totales": "Итоги",
    "Total": "Общее",
    "Consultar": "Проконсультируйтесь",
    "N°. Factura":"Нет. выставленный счет",
    "N. de documento":"Документ №.",
    "T. de documento":"Размер документа",
    "No hay información encontrada":"Информация не найдена"

};
